export const defaultBestMatches: InstrumentBestMatch[] = [
    {
        symbol: "GOOGL",
        shortname: "Alphabet Inc.",
        longname: "Alphabet Inc.",
        exchDisp: "NASDAQ",
        quoteType: "EQUITY",
        industry: "Internet Content & Information",
    },
    {
        symbol: "AAPL",
        shortname: "Apple Inc.",
        longname: "Apple Inc.",
        exchDisp: "NASDAQ",
        quoteType: "EQUITY",
        industry: "Consumer Electronics",
    },
    {
        symbol: "AMZN",
        shortname: "Amazon.com, Inc.",
        longname: "Amazon.com, Inc.",
        exchDisp: "NASDAQ",
        quoteType: "EQUITY",
        industry: "Internet Retail",
    },
    {
        symbol: "META",
        shortname: "Meta Platforms, Inc.",
        longname: "Meta Platforms, Inc.",
        exchDisp: "NASDAQ",
        quoteType: "EQUITY",
        industry: "Internet Content & Information",
    },
    {
        symbol: "MSFT",
        shortname: "Microsoft Corporation",
        longname: "Microsoft Corporation",
        exchDisp: "NASDAQ",
        quoteType: "EQUITY",
        industry: "Software—Infrastructure",
    },
    {
        symbol: "TSLA",
        shortname: "Tesla, Inc.",
        longname: "Tesla, Inc.",
        exchDisp: "NASDAQ",
        quoteType: "EQUITY",
        industry: "Auto Manufacturers",
    },
];